In [1]:
import cv2
import numpy as np

In [2]:
data = np.load('../data/stereo/case1/stereo.npy', allow_pickle=True).item()
Kl, Kr, Dl, Dr, left_pts, right_pts, E_from_stereo, F_from_stereo = \
    data['Kl'], data['Kr'], data['Dl'], data['Dr'], \
    data['left_pts'], data['right_pts'], data['E'], data['F']

In [3]:
left_pts = np.vstack(left_pts)
right_pts = np.vstack(right_pts)

In [4]:
left_pts = cv2.undistortPoints(left_pts, Kl, Dl, P=Kl)
right_pts = cv2.undistortPoints(right_pts, Kr, Dr, P=Kr)

In [6]:
F, mask = cv2.findFundamentalMat(left_pts, right_pts, cv2.FM_LMEDS)

In [7]:
F

array([[ 1.60938825e-08, -2.23906409e-06, -2.53850603e-04],
       [ 2.97226703e-06, -2.38236386e-07, -7.70276666e-02],
       [-2.55190056e-04,  7.69760820e-02,  1.00000000e+00]])

In [8]:
E = Kr.T @ F @ Kl

In [9]:
print('Fundamental matrix:')
print(F)
print('Essential matrix:')
print(E)

Fundamental matrix:
[[ 1.60938825e-08 -2.23906409e-06 -2.53850603e-04]
 [ 2.97226703e-06 -2.38236386e-07 -7.70276666e-02]
 [-2.55190056e-04  7.69760820e-02  1.00000000e+00]]
Essential matrix:
[[ 4.62585055e-03 -6.43487140e-01 -4.17486092e-01]
 [ 8.53590806e-01 -6.84088948e-02 -4.08817705e+01]
 [ 2.63679084e-01  4.07046349e+01 -2.20825664e-01]]
