In [1]:
import cv2
import numpy as np

In [2]:
P1 = np.eye(3, 4, dtype=np.float32)
P2 = np.eye(3, 4, dtype=np.float32)
P2[0, 3] = -1

In [4]:
N = 5
points3d = np.empty((4, N), np.float32)
points3d[:3, :] = np.random.randn(3, N)
points3d[3, :] = 1

In [5]:
points1 = P1 @ points3d
points1 = points1[:2, :] / points1[2, :]
points1[:2, :] += np.random.randn(2, N) * 1e-2

points2 = P2 @ points3d
points2 = points2[:2, :] / points2[2, :]
points2[:2, :] += np.random.randn(2, N) * 1e-2

In [6]:
points3d_reconstr = cv2.triangulatePoints(P1, P2, points1, points2)
points3d_reconstr /= points3d_reconstr[3, :]

In [7]:
print('Original points')
print(points3d[:3].T)
print('Reconstructed points')
print(points3d_reconstr[:3].T)

Original points
[[ 1.081279   -0.99633145 -0.84461826]
 [-0.13421062 -0.1097857   0.98051167]
 [ 0.03670051  0.6888201  -0.56386214]
 [-0.38759682  0.8961643   0.84851336]
 [-0.45612594  0.08040986 -0.10995554]]
Reconstructed points
[[ 1.0678916  -0.9838293  -0.83585995]
 [-0.13354994 -0.09540577  0.9745699 ]
 [ 0.03198474  0.685727   -0.5613085 ]
 [-0.4050801   0.90336996  0.85936534]
 [-0.45492786  0.07963713 -0.10996541]]
