In [1]:
import cv2
import numpy as np

In [2]:
K = np.array([[560,0,320],[0,560,240],[0,0,1]],dtype=np.float32)
rvec = np.array([0.1, 0.2, 0.3], np.float32)
R, _ = cv2.Rodrigues(rvec)
print(R)

[[ 0.9357548  -0.28316498  0.21019171]
 [ 0.30293274  0.9505806  -0.06803132]
 [-0.18054008  0.12733458  0.9752903 ]]


In [3]:
H = K @ R @ np.linalg.inv(K)

In [4]:
H /= H[2, 2]

In [6]:
print(H)

[[ 8.1316733e-01 -2.0549431e-01  2.0887941e+02]
 [ 2.2029683e-01  9.8170549e-01 -1.1470359e+02]
 [-3.1487257e-04  2.2207903e-04  1.0000000e+00]]


In [7]:
H += np.random.randn(3,3)*0.0001

In [8]:
np.save('rotational_homography.npy', {'H': H, 'K': K})

In [10]:
data = np.load('../data/rotational_homography.npy', allow_pickle=True).item()
H, K = data['H'], data['K']

In [12]:
H_ = np.linalg.inv(K) @ H @ K

w, u, vt = cv2.SVDecomp(H_)
R = u @ vt
if cv2.determinant(R) < 0:
    R *= 1

In [14]:
rvec = cv2.Rodrigues(R)[0]

print('Rotation vector:')
print(rvec)

Rotation vector:
[[0.12439562]
 [0.22688715]
 [0.3264132 ]]
