In [1]:
import torch
import numpy as np

### 텐서 초기화

In [2]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [9]:
x_ones = torch.ones_like(x_data)
print(f"ones tensor: \n{x_ones}")

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"random tensor: \n {x_rand}")

ones tensor: 
tensor([[1, 1],
        [1, 1]])
random tensor: 
 tensor([[0.1889, 0.2662],
        [0.4521, 0.6507]])


In [13]:
shape = (2, 3, )
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"random tensor: \n{rand_tensor}")
print(f"ones tensor: \n{ones_tensor}")
print(f"zeros tensor: \n{zeros_tensor}")

random tensor: 
tensor([[0.1259, 0.4496, 0.8550],
        [0.2834, 0.8433, 0.8496]])
ones tensor: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])
zeros tensor: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])


### 텐서 속성

In [15]:
tensor = torch.rand(3,4)

print(f"shape of tensor: {tensor.shape}")
print(f"datatype of tensor: {tensor.dtype}")
print(f"device of tensor: {tensor.device}")

shape of tensor: torch.Size([3, 4])
datatype of tensor: torch.float32
device of tensor: cpu


### 텐서 연산

In [16]:
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

In [20]:
tensor = torch.ones(4, 4)
print(f"first row: {tensor[0]}")
print(f"first column: {tensor[:,0]}")
print(f"last column: {tensor[...,-1]}")
tensor[:, 1] = 0
print(tensor)

first row: tensor([1., 1., 1., 1.])
first column: tensor([1., 1., 1., 1.])
last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [21]:
t1 = torch.cat([tensor, tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [39]:
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [40]:
z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [41]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


In [43]:
print(tensor, '\n')
tensor.add_(5) # in-place 연산
print(tensor)

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]]) 

tensor([[11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.]])


### Numpy 변환(Bridge)

In [45]:
# cpu 상의 텐서와 numpy 배열은 메모리공간을 공유해서 하나를 변경하면 다른 하나도 변경됨
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [46]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


### numpy 배열을 텐서로 변환

In [50]:
n = np.ones(5)
t = torch.from_numpy(n)

In [51]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
