In [1]:
import torch
import numpy as np

In [2]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [9]:
x_ones = torch.ones_like(x_data)
print(f"ones tensor: \n{x_ones}")

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"random tensor: \n {x_rand}")

ones tensor: 
tensor([[1, 1],
        [1, 1]])
random tensor: 
 tensor([[0.1889, 0.2662],
        [0.4521, 0.6507]])


In [13]:
shape = (2, 3, )
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"random tensor: \n{rand_tensor}")
print(f"ones tensor: \n{ones_tensor}")
print(f"zeros tensor: \n{zeros_tensor}")

random tensor: 
tensor([[0.1259, 0.4496, 0.8550],
        [0.2834, 0.8433, 0.8496]])
ones tensor: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])
zeros tensor: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])
